inputs:
- name: dnsacc
  type: m3u
  url: "${env:DNSACC_M3U_URL}"
  cache_duration: 1d
  max_connections: 0
- name: cldnew
  type: m3u
  url: "${env:CLDNEW_M3U_URL}"
  enabled: false
  max_connections: 0
- name: biturl
  type: m3u
  url: "${env:BITURL_M3U_URL}"
  max_connections: 0
- name: firetvcb
  type: m3u
  url: "${env:FIRETVCB_M3U_URL}"
  max_connections: 0
sources:
- inputs:
  - dnsacc
  targets:
  - name: dnsacc
    output:
    - type: xtream
    - type: m3u
      filename: dnsacc.m3u
- inputs:
  - cldnew
  targets:
  - enabled: false
    name: cldnew
    output:
    - type: xtream
    - type: m3u
      filename: cldnew.m3u
- inputs:
  - biturl
  targets:
  - name: biturl
    output:
    - type: xtream
    - type: m3u
      filename: biturl.m3u
- inputs:
  - firetvcb
  targets:
  - name: firetvcb
    output:
    - type: xtream
    - type: m3u
      filename: firetvcb.m3u
