templates:
- name: not_red_button
  value: NOT (Title ~ "(?i).*red button.*")
- name: not_low_resolution
  value: NOT (Title ~ "(?i).*\(360p|240p\).*")
- name: all_channels
  value: Title ~ ".*"
- name: final_channel_lineup
  value: "!all_channels! AND !not_red_button! AND !not_low_resolution!"
